/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CategoryDropdown: typeof import('./src/components/Category/CategoryDropdown.vue')['default']
    CategoryForm: typeof import('./src/components/Category/CategoryForm.vue')['default']
    CategoryM: typeof import('./src/components/Category/CategoryManagement.vue')['default']
    CategoryManagement: typeof import('./src/components/Category/CategoryManagement.vue')['default']
    CategoryTable: typeof import('./src/components/Category/CategoryTable.vue')['default']
    CreateUpdateCategory: typeof import('./src/components/Category/CreateUpdateCategory.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    PreviewSession: typeof import('./src/components/Category/PreviewSession.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionTable: typeof import('./src/components/Category/SessionTable.vue')['default']
  }
}
